inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4
  DisplayCopNames: true
  Include:
    - 'Capfile'
    - 'Rakefile'
    - 'config.ru'
    - '**/*.rb'
    - '**/*.rake'
    - 'Gemfile'
  Exclude:
    - 'bin/**/*'
    - 'config/environments/*.rb'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
